language: node_js
node_js:
  - "6"
  - "7"
  - "8"

before_install:
  - npm install -g yarn --cache-min 999999999

install:
  - yarn

script:
- npm run build:dev
- npm run build:prod

cache:
  directories:
    - node_modules